import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Footer from '../components/Footer';
import Herosection from './herosection';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Contract 308</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Herosection />
      <Footer />
    </div>
  );
}
